name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # ... (existing steps)

      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Push to Docker Hub
        run: |
          docker push your-dockerhub-omer07/docker1098:latest || exit 0

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Set up SSH connection to EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          debug: true

      - name: Pull Docker image from Docker Hub on EC2 instance
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secret


