name: Deploy Node.app.js

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Create Node.app.js
        run: |
          echo "console.log('Hello, World I Omer Abdullah From Switzerland I am Coming On the way to India')" > app.js
          npm install

      - name: Create Dockerfile
        run: |
          echo "FROM node:alpine\nCOPY . .\nCMD [\"node\", \"app.js\"]" > Dockerfile

      - name: Commit Changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Auto-commit changes"

      - name: Push Changes
        run: |
          git push origin main

      - name: Connect to EC2 instance
        run: |
          ssh-keyscan -H ${{ secrets.EC2_PUBLIC_IP }} >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/id_rsa
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_PUBLIC_IP }} 'echo Successfully connected'

      - name: Install Docker on EC2
        run: |
          sudo yum update -y 
          sudo yum install docker -y

      - name: Login to Docker Hub on EC2
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Pull image on EC2
        run: docker pull $DOCKER_USERNAME/nodeapp:latest

      - name: Run container on EC2
        run: docker run -d --name nodeapp $DOCKER_USERNAME/nodeapp

      - name: My Step
        run: |
          set -x
          # Your additional debugging commands here
          echo "Debugging step: Hello from My Step"

