name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Build Docker image
        run: docker build -t your-dockerhub-omer07/docker1098:latest .

      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Push to Docker Hub
        run: |
          docker push your-dockerhub-omer07/docker1098:latest || exit 0

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up EC2 Instance Connect
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: 22
          debug: true

      - name: Install Docker on EC2
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io

      - name: Log in to Docker Hub on EC2
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull Docker image on EC2
        run: |
          docker pull your-dockerhub-omer07/docker1098:latest

      - name: Run Docker container on EC2
        run: |
          docker run -d -p 4500:4500 your-dockerhub-omer07/docker1098:latest
